SHELL = /bin/sh


all: data_compile data_dict

data_compile:
	./data_compile.sh
data_dict:
	./data_dict.sh

clean:
	rm -f ../*.c
	rm -f ../const.h
	rm -f ../dict_final
	rm -f ../pdgm_offset_info
	rm -f ../suff
	rm -f ../uword.dbm
